# Generated by Django 4.2.5 on 2023-09-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feature',
            new_name='featured',
        ),
    ]
